# -*- coding: utf-8 -*-
"""Game Tebak Angka.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IMpTQrt34Dx7ccOE-1khMiORVqehO1kB
"""

import random

angka_rahasia = random.randint(1, 100)
tebakan = 0

while tebakan != angka_rahasia:
    tebakan = int(input("Tebak angka (1-100): "))

    if tebakan >= 1 and tebakan <= 100:
        if tebakan > angka_rahasia:
            print("Tebakan terlalu besar")
        elif tebakan < angka_rahasia:
            print("Tebakan terlalu kecil")
        else:
            print(" Selamat! Tebakan kamu benar")
    else:
        print("Masukkan angka antara 1 sampai 10")